### ISSUE TITLE
loss of fullname for setters on using retyper.typecheck twice

### ISSUE THREAD

**Issue by drcicero** [stg-tud/retypecheck#1] opened 2019-09-30 14:18 UTC
I'm using "de.tuda.stg" %% "retypecheck" % "0.6.0".

I noticed, that by applying retyper.typecheck twice (as in `retyper.typecheck(retyper.typecheck(x))`), we loose the full package name resolution of setters(, but not of getters). Attached is code to reproduce the bug, but first the output that should be equal but is not:

~~~scala
def f(): Unit = X.this.x_=(X.this.x.+(1)) // output of re.typecheck(code)
def f(): Unit =        x_=(X.this.x.+(1)) // output of re.typecheck(re.typecheck(code))
~~~

Now, here is the whole code to reproduce it:

~~~scala
val code = q"class X { var x: Int = 0; def f() = { x = x + 1; } }"
println("code " + code)
println("typecheck " + c.typecheck(code))
println("twicecheck " + c.typecheck(c.typecheck(code)))
println("re.typecheck " + c.retyper.typecheck(code))
println("re.twicecheck " + c.retyper.typecheck(c.retyper.typecheck(code)))
~~~

Output shows that 'typecheck' == 'twicecheck', but 're.typecheck' != 're.twicecheck':

~~~scala
code class X extends scala.AnyRef {
  def <init>() = {
    super.<init>();
    ()
  };
  var x: Int = 0;
  def f() = x = x.$plus(1)
}

typecheck class X extends scala.AnyRef {
  def <init>(): X = {
    X.super.<init>();
    ()
  };
  private[this] var x: Int = 0;
  <accessor> def x: Int = X.this.x;
  <accessor> def x_=(x$1: Int): Unit = X.this.x = x$1;
  def f(): Unit = X.this.x_=(X.this.x.+(1))
}

twicecheck class X extends scala.AnyRef {
  def <init>(): X = {
    X.super.<init>();
    ()
  };
  private[this] var x: Int = 0;
  <accessor> def x: Int = X.this.x;
  <accessor> def x_=(x$1: Int): Unit = X.this.x = x$1;
  def f(): Unit = X.this.x_=(X.this.x.+(1))
}

re.typecheck class X extends _root_.scala.AnyRef {
  def <init>(): X = {
    X.super.<init>();
    ()
  };
  <accessor> val x: Int = 0;
  def f(): Unit = X.this.x_=(X.this.x.+(1))
}

re.twicecheck class X extends _root_.scala.AnyRef {
  def <init>(): X = {
    X.super.<init>();
    ()
  };
  <accessor> val x: Int = 0;
  def f(): Unit = x_=(X.this.x.+(1))
}
~~~

EDIT: Workaround is to just not call retype.typecheck twice. It was an accident anyway. :)

**Comment by pweisenburger** [comment] 2020-12-28 21:30
Good catch! Finally, I got to investigate this issue. That behavior might indeed lead to problems although, in this specific example, the code before and after the second `typecheck` is functionally equivalent. In general, `typecheck` might not be idempotent wrt. structural equivalence of the ASTs.

The issue is fixed in a515e48851edd8a74574f92a9d2e468e94c989a5. Also since cf3ca9180bc785b4cdf6d2f3c7c401a4bbb0f39f, `val x: Int = 0` is correctly printed as `var x: Int = 0`.

**Closed as completed** 2020-12-28 22:39 UTC
